### ISSUE TITLE
Unhelpful error when running action

### ISSUE THREAD

**Issue by daniel-vc** [stefanoeb/eslint-action#8]
Hi, I'm trying to use your linting action but even though i've followed your set up steps, and running eslint locally, I get the below message. Any ideas?

<img width="627" alt="Screenshot 2020-03-11 at 16 16 44" src="https://user-images.githubusercontent.com/39903900/76439127-d6aa4400-63b3-11ea-8caf-516e1176621a.png">

**Comment by stefanoeb** [comment]
hey @daniel-vc 

Looks like it's a problem with your tests themselves regarding promise chaining.

Just to clarify: does it reproduce locally?

**Comment by noftaly** [comment]
Hi, I have the same issue, and no, it is only in the actions. I don't have those messages locally. For me, it comes from your action!
You can see it right here: https://github.com/Skript-MC/Swan/runs/533285405?check_suite_focus=true

**Comment by gslama-akqa** [comment]
Hi there, I can confirm I'm getting the same warning.

**Comment by abmusse** [comment]
@stefanoeb 

I also experienced this issue and found that it is caused by this issue https://npm.community/t/npm-ci-produces-a-tonn-of-excess-warnings-on-install/3261.

This can be fixed by upgrading the nodejs image used in the docker file. I tested using nodejs 12 (current LTS) and this issue went away. I Opened up #10 to help resolve the issue.

**Comment by rdzak** [comment]
I had to remove this action from the workflow due to the same error. I'll be watching this issue to verify it's fixed with proposed solution (node upgrade)

**Comment by stefanoeb** [comment]
I would actually recommend running ESLint without this action, because out of the box the ubuntu runtime of Github Action has everything we need now, like so:
```yml
name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Lint
      run: eslint .
```
